# Generated by Django 4.2.3 on 2023-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='kitobga_kirish',
            field=models.TextField(blank=True),
        ),
    ]
