# Generated by Django 4.2.3 on 2023-09-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0002_kitob_kitobga_kirish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='kitobga_kirish',
            new_name='kitobga_matn',
        ),
    ]
