# Generated by Django 4.2.3 on 2023-09-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0003_rename_kitobga_kirish_kitob_kitobga_matn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitob',
            old_name='kitobga_matn',
            new_name='kitob_matni',
        ),
    ]
